### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by sido420** [TehShrike/sveltify#13]
I am new to frontend build process and Svelte so might be asking a very basic question here.

I have a project that uses old style javascript script tags to include files to the page and simply use the libraries using Backbone, $ etc (no import, require etc stuff yet due to some limitations). 

I want to use Svelte components in some parts of the app and not sure how I could do that without import etc. Through some research I figured out that this might be the right solution to use however I am getting the following error when I run it on the svelte template project.

```
Error: Cannot find module '/projects/svelte-comps/src/dist/myfile.js' from '/projects/svelte-comps/src'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```

I have already installed  `npm i --save-dev sveltify@3` in project folder.

Also,
```
$ browserify --version
16.2.2
```

**Settings in root obj of `package.json`**
```
  "browserify": {
    "transform": [
      [
        "sveltify",
        {
          "svelte": {
            "dev": true
          },
          "extensions": [
            ".html",
            ".svelte"
          ]
        }
      ]
    ]
  },
```

**Comment by TehShrike** [comment]
I think what you want is [the regular Svelte template](https://github.com/sveltejs/template/), which defaults to building to a [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression).

Then you can change https://github.com/sveltejs/template/blob/master/src/main.js to whatever you want, or if you want to just use the component elsewhere on the page, you can delete that file entirely and change the project to build `App.svelte` directly.
